// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scheduler/v1/scheduler.proto

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotRank int32

const (
	SlotRank_SLOT_RANK_UNSPECIFIED SlotRank = 0
	SlotRank_SLOT_RANK_AVAILABLE   SlotRank = 1
	SlotRank_SLOT_RANK_PREFERRED   SlotRank = 2
)

// Enum value maps for SlotRank.
var (
	SlotRank_name = map[int32]string{
		0: "SLOT_RANK_UNSPECIFIED",
		1: "SLOT_RANK_AVAILABLE",
		2: "SLOT_RANK_PREFERRED",
	}
	SlotRank_value = map[string]int32{
		"SLOT_RANK_UNSPECIFIED": 0,
		"SLOT_RANK_AVAILABLE":   1,
		"SLOT_RANK_PREFERRED":   2,
	}
)

func (x SlotRank) Enum() *SlotRank {
	p := new(SlotRank)
	*p = x
	return p
}

func (x SlotRank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlotRank) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (SlotRank) Type() protoreflect.EnumType {
	return &file_scheduler_v1_scheduler_proto_enumTypes[0]
}

func (x SlotRank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlotRank.Descriptor instead.
func (SlotRank) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

type BookingStatus int32

const (
	BookingStatus_BOOKING_STATUS_UNSPECIFIED BookingStatus = 0
	BookingStatus_BOOKING_STATUS_CONFIRMED   BookingStatus = 1
	BookingStatus_BOOKING_STATUS_CONFLICT    BookingStatus = 2
)

// Enum value maps for BookingStatus.
var (
	BookingStatus_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_CONFIRMED",
		2: "BOOKING_STATUS_CONFLICT",
	}
	BookingStatus_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_CONFIRMED":   1,
		"BOOKING_STATUS_CONFLICT":    2,
	}
)

func (x BookingStatus) Enum() *BookingStatus {
	p := new(BookingStatus)
	*p = x
	return p
}

func (x BookingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_v1_scheduler_proto_enumTypes[1].Descriptor()
}

func (BookingStatus) Type() protoreflect.EnumType {
	return &file_scheduler_v1_scheduler_proto_enumTypes[1]
}

func (x BookingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingStatus.Descriptor instead.
func (BookingStatus) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

type CalendarEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`     // RFC3339 timestamp
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`         // RFC3339 timestamp
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"` // Event title
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarEvent) Reset() {
	*x = CalendarEvent{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarEvent) ProtoMessage() {}

func (x *CalendarEvent) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarEvent.ProtoReflect.Descriptor instead.
func (*CalendarEvent) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *CalendarEvent) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *CalendarEvent) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *CalendarEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"` // RFC3339 timestamp
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`     // RFC3339 timestamp
	Rank          SlotRank               `protobuf:"varint,3,opt,name=rank,proto3,enum=scheduler.v1.SlotRank" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *TimeSlot) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TimeSlot) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *TimeSlot) GetRank() SlotRank {
	if x != nil {
		return x.Rank
	}
	return SlotRank_SLOT_RANK_UNSPECIFIED
}

type GetAvailabilityRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ScheduleLinkId        string                 `protobuf:"bytes,1,opt,name=schedule_link_id,json=scheduleLinkId,proto3" json:"schedule_link_id,omitempty"`
	WindowStart           string                 `protobuf:"bytes,2,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"` // RFC3339 timestamp
	WindowEnd             string                 `protobuf:"bytes,3,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`       // RFC3339 timestamp
	InviteeTimezone       string                 `protobuf:"bytes,4,opt,name=invitee_timezone,json=inviteeTimezone,proto3" json:"invitee_timezone,omitempty"`
	InviteeCalendarEvents []*CalendarEvent       `protobuf:"bytes,5,rep,name=invitee_calendar_events,json=inviteeCalendarEvents,proto3" json:"invitee_calendar_events,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetAvailabilityRequest) Reset() {
	*x = GetAvailabilityRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityRequest) ProtoMessage() {}

func (x *GetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *GetAvailabilityRequest) GetScheduleLinkId() string {
	if x != nil {
		return x.ScheduleLinkId
	}
	return ""
}

func (x *GetAvailabilityRequest) GetWindowStart() string {
	if x != nil {
		return x.WindowStart
	}
	return ""
}

func (x *GetAvailabilityRequest) GetWindowEnd() string {
	if x != nil {
		return x.WindowEnd
	}
	return ""
}

func (x *GetAvailabilityRequest) GetInviteeTimezone() string {
	if x != nil {
		return x.InviteeTimezone
	}
	return ""
}

func (x *GetAvailabilityRequest) GetInviteeCalendarEvents() []*CalendarEvent {
	if x != nil {
		return x.InviteeCalendarEvents
	}
	return nil
}

type GetAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*TimeSlot            `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailabilityResponse) Reset() {
	*x = GetAvailabilityResponse{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityResponse) ProtoMessage() {}

func (x *GetAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *GetAvailabilityResponse) GetSlots() []*TimeSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type CreateBookingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScheduleLinkId   string                 `protobuf:"bytes,1,opt,name=schedule_link_id,json=scheduleLinkId,proto3" json:"schedule_link_id,omitempty"`
	StartTime        string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // RFC3339 timestamp
	EndTime          string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // RFC3339 timestamp
	AttendeeName     string                 `protobuf:"bytes,4,opt,name=attendee_name,json=attendeeName,proto3" json:"attendee_name,omitempty"`
	AttendeeEmail    string                 `protobuf:"bytes,5,opt,name=attendee_email,json=attendeeEmail,proto3" json:"attendee_email,omitempty"`
	AttendeeTimezone string                 `protobuf:"bytes,6,opt,name=attendee_timezone,json=attendeeTimezone,proto3" json:"attendee_timezone,omitempty"`
	Notes            string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBookingRequest) GetScheduleLinkId() string {
	if x != nil {
		return x.ScheduleLinkId
	}
	return ""
}

func (x *CreateBookingRequest) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreateBookingRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreateBookingRequest) GetAttendeeName() string {
	if x != nil {
		return x.AttendeeName
	}
	return ""
}

func (x *CreateBookingRequest) GetAttendeeEmail() string {
	if x != nil {
		return x.AttendeeEmail
	}
	return ""
}

func (x *CreateBookingRequest) GetAttendeeTimezone() string {
	if x != nil {
		return x.AttendeeTimezone
	}
	return ""
}

func (x *CreateBookingRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Status        BookingStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=scheduler.v1.BookingStatus" json:"status,omitempty"`
	MeetingUrl    string                 `protobuf:"bytes,3,opt,name=meeting_url,json=meetingUrl,proto3" json:"meeting_url,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CreateBookingResponse) GetStatus() BookingStatus {
	if x != nil {
		return x.Status
	}
	return BookingStatus_BOOKING_STATUS_UNSPECIFIED
}

func (x *CreateBookingResponse) GetMeetingUrl() string {
	if x != nil {
		return x.MeetingUrl
	}
	return ""
}

func (x *CreateBookingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBookingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x1cscheduler/v1/scheduler.proto\x12\fscheduler.v1\"Q\n" +
	"\rCalendarEvent\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\"^\n" +
	"\bTimeSlot\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\x12*\n" +
	"\x04rank\x18\x03 \x01(\x0e2\x16.scheduler.v1.SlotRankR\x04rank\"\x84\x02\n" +
	"\x16GetAvailabilityRequest\x12(\n" +
	"\x10schedule_link_id\x18\x01 \x01(\tR\x0escheduleLinkId\x12!\n" +
	"\fwindow_start\x18\x02 \x01(\tR\vwindowStart\x12\x1d\n" +
	"\n" +
	"window_end\x18\x03 \x01(\tR\twindowEnd\x12)\n" +
	"\x10invitee_timezone\x18\x04 \x01(\tR\x0finviteeTimezone\x12S\n" +
	"\x17invitee_calendar_events\x18\x05 \x03(\v2\x1b.scheduler.v1.CalendarEventR\x15inviteeCalendarEvents\"G\n" +
	"\x17GetAvailabilityResponse\x12,\n" +
	"\x05slots\x18\x01 \x03(\v2\x16.scheduler.v1.TimeSlotR\x05slots\"\x89\x02\n" +
	"\x14CreateBookingRequest\x12(\n" +
	"\x10schedule_link_id\x18\x01 \x01(\tR\x0escheduleLinkId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12#\n" +
	"\rattendee_name\x18\x04 \x01(\tR\fattendeeName\x12%\n" +
	"\x0eattendee_email\x18\x05 \x01(\tR\rattendeeEmail\x12+\n" +
	"\x11attendee_timezone\x18\x06 \x01(\tR\x10attendeeTimezone\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"\xb1\x01\n" +
	"\x15CreateBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.scheduler.v1.BookingStatusR\x06status\x12\x1f\n" +
	"\vmeeting_url\x18\x03 \x01(\tR\n" +
	"meetingUrl\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"5\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"K\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*W\n" +
	"\bSlotRank\x12\x19\n" +
	"\x15SLOT_RANK_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SLOT_RANK_AVAILABLE\x10\x01\x12\x17\n" +
	"\x13SLOT_RANK_PREFERRED\x10\x02*j\n" +
	"\rBookingStatus\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18BOOKING_STATUS_CONFIRMED\x10\x01\x12\x1b\n" +
	"\x17BOOKING_STATUS_CONFLICT\x10\x022\xa6\x02\n" +
	"\x10SchedulerService\x12^\n" +
	"\x0fGetAvailability\x12$.scheduler.v1.GetAvailabilityRequest\x1a%.scheduler.v1.GetAvailabilityResponse\x12X\n" +
	"\rCreateBooking\x12\".scheduler.v1.CreateBookingRequest\x1a#.scheduler.v1.CreateBookingResponse\x12X\n" +
	"\rCancelBooking\x12\".scheduler.v1.CancelBookingRequest\x1a#.scheduler.v1.CancelBookingResponseB>Z<github.com/meetflow/scheduler/proto/scheduler/v1;schedulerv1b\x06proto3"

var (
	file_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_v1_scheduler_proto_rawDesc), len(file_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_scheduler_v1_scheduler_proto_rawDescData
}

var file_scheduler_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_scheduler_v1_scheduler_proto_goTypes = []any{
	(SlotRank)(0),                   // 0: scheduler.v1.SlotRank
	(BookingStatus)(0),              // 1: scheduler.v1.BookingStatus
	(*CalendarEvent)(nil),           // 2: scheduler.v1.CalendarEvent
	(*TimeSlot)(nil),                // 3: scheduler.v1.TimeSlot
	(*GetAvailabilityRequest)(nil),  // 4: scheduler.v1.GetAvailabilityRequest
	(*GetAvailabilityResponse)(nil), // 5: scheduler.v1.GetAvailabilityResponse
	(*CreateBookingRequest)(nil),    // 6: scheduler.v1.CreateBookingRequest
	(*CreateBookingResponse)(nil),   // 7: scheduler.v1.CreateBookingResponse
	(*CancelBookingRequest)(nil),    // 8: scheduler.v1.CancelBookingRequest
	(*CancelBookingResponse)(nil),   // 9: scheduler.v1.CancelBookingResponse
}
var file_scheduler_v1_scheduler_proto_depIdxs = []int32{
	0, // 0: scheduler.v1.TimeSlot.rank:type_name -> scheduler.v1.SlotRank
	2, // 1: scheduler.v1.GetAvailabilityRequest.invitee_calendar_events:type_name -> scheduler.v1.CalendarEvent
	3, // 2: scheduler.v1.GetAvailabilityResponse.slots:type_name -> scheduler.v1.TimeSlot
	1, // 3: scheduler.v1.CreateBookingResponse.status:type_name -> scheduler.v1.BookingStatus
	4, // 4: scheduler.v1.SchedulerService.GetAvailability:input_type -> scheduler.v1.GetAvailabilityRequest
	6, // 5: scheduler.v1.SchedulerService.CreateBooking:input_type -> scheduler.v1.CreateBookingRequest
	8, // 6: scheduler.v1.SchedulerService.CancelBooking:input_type -> scheduler.v1.CancelBookingRequest
	5, // 7: scheduler.v1.SchedulerService.GetAvailability:output_type -> scheduler.v1.GetAvailabilityResponse
	7, // 8: scheduler.v1.SchedulerService.CreateBooking:output_type -> scheduler.v1.CreateBookingResponse
	9, // 9: scheduler.v1.SchedulerService.CancelBooking:output_type -> scheduler.v1.CancelBookingResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scheduler_v1_scheduler_proto_init() }
func file_scheduler_v1_scheduler_proto_init() {
	if File_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_v1_scheduler_proto_rawDesc), len(file_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_scheduler_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_v1_scheduler_proto = out.File
	file_scheduler_v1_scheduler_proto_goTypes = nil
	file_scheduler_v1_scheduler_proto_depIdxs = nil
}
